server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #表示是否将自己注册到Eureka Server，默认为true，由于当前应用就是Eureka Server，故为false
    fetch-registry: false  #表示是否从Eureka Server获取注册信息，默认为true，因为是单点Eureka Server，不需要同步其它Eureka Server节点数据，故false
    service-url:  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka;多个地址使用，分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
